name: Build and Deploy Web Application

on:
  push:
    branches:
      - main  # Déclenchement automatique lors d'un push sur la branche main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Récupérer le code source du dépôt

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Définir la version de .NET (ajustez selon votre version de .NET)

    - name: Restore dependencies
      run: |
        dotnet restore ./CalicotEncheres/Auctions/Auctions.csproj  # Restaurer les dépendances du projet spécifique

    - name: Build the application
      run: |
        dotnet build ./CalicotEncheres/Auctions/Auctions.csproj --configuration Release  # Compiler l'application

    - name: Publish the application
      run: |
        dotnet publish ./CalicotEncheres/Auctions/Auctions.csproj --configuration Release --output ./publish  # Publier

    ##- name: Set up Azure CLI
    ##  uses: azure/cli-action@v1
    ##  with:
    ##    azcliversion: 2.39.0  # Version de l'Azure CLI à utiliser

    ##- name: Azure login
    ##  uses: azure/login@v1
    ##  with:
    ##    creds: ${{ secrets.AZURE_CREDENTIALS }}  # Utilisez un secret GitHub pour stocker les informations d'authentification Azure

    ##- name: Deploy to Azure App Service
    ##  run: |
    ##    az webapp deploy --resource-group <ResourceGroup> --name <AppName> --src-path ./publish  # Déployer l'application sur Azure App Service
